### ISSUE TITLE
FreeCAD

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/homelab#193]
FreeCAD
```yaml
version: '3.8'
services:
  freecad:
    image: lscr.io/linuxserver/freecad:latest
    container_name: freecad
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/your/config:/config
    ports:
      - 3000:3000
    shm_size: '1gb'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```
